export const INDENT_ACTION = {
    GET_INDENT_LIST : 'GET_INDENT_LIST',
    GET_INDENT_LIST_RESPONSE : 'GET_INDENT_LIST_RESPONSE',
    ADD_INDENT_LIST : 'ADD_INDENT_LIST',
    ADD_INDENT_LIST_RESPONSE : 'ADD_INDENT_LIST_RESPONSE',
    
}